/*
 * This file has been generated by the KUIP compiler.  Do NOT change it!
 *
 * KUIP header: 950303      Generation date: Tue Feb 24 14:29:46 2004
 *
 * Input file: guinti.cdf
 */

#if !defined(F77_LCASE) && !defined(F77_UCASE) && !defined(F77_USCORE)
#  if defined(__EXTENDED__) && !defined(IBM370) && !defined(_IBMR2)
#    define IBM370
#  endif
#  if defined(CRAY) || defined(IBM370) || defined(vms)
#    define F77_UCASE
#  else
#    if ( defined(apollo) || defined(__apollo) ) && defined(APOFTN)
#      define F77_LCASE
#    else
#      define F77_USCORE
#    endif
#  endif
#endif

#if (defined(WIN32)||defined(CERNLIB_WINNT)) && defined(CERNLIB_MSSTDCALL)
#ifndef F77_UCASE
#define F77_UCASE
#endif
#define type_of_call _stdcall
#endif
#ifndef type_of_call
#  define type_of_call
#endif

typedef int     IntFunc();
typedef char*   CharFunc();
typedef char** pCharFunc();
typedef void  type_of_call  SUBROUTINE();
#ifdef IBM370
#  pragma linkage(SUBROUTINE,FORTRAN)
#endif

extern void klnkmenu();
extern void klnkbrcl();
extern void klnkkmcl();
extern void klnkicon();
extern void klnkbutt();

typedef unsigned long KmPixmap; /* Pixmap from <X11/X.h>                   */
 typedef void *KmWidget;         /* Widget from <X11/Intrinsic.h>           */
 typedef void *KmCalldata;       /* XmAnyCallbackStruct from <Motif/Xm.h>   */
                                 /*                                         */
 typedef enum {                  /*                                         */
   BRACT_OPEN = 0,               /*                                         */
   BRACT_ROOT = 1,               /*                                         */
   BRACT_CONT = 2,               /*                                         */
   BRACT_GRAF = 3                /*                                         */
 } BrActTag;                     /*                                         */
                                 /*                                         */
 typedef enum {                  /*                                         */
   BrActUpdate    = 0x01,        /* browser window has to be updated ('!')  */
   BrActSeparator = 0x02,        /* put separator in menu ('/')             */
   BrActToggle    = 0x04,        /* register as toggle button               */
   BrActToggleOn  = 0x08,        /* toggle state is on                      */
   BrActSensitive = 0x10         /* button is sensitive                     */
 } BrActFlag;                    /*                                         */
                                 /*                                         */ 

typedef struct _BrAction {      /*                                         */ 
  struct _BrAction *next;       /* link to next action binding             */ 
  BrActFlag   flags;            /*                                         */ 
  char       *text;             /* text line in menu                       */ 
  char       *user_text;        /* user text overriding CDF text (malloced)*/ 
  char       *accel;            /* accelerator                             */ 
  char       *exec;             /* action commands                         */ 
  SUBROUTINE *call_F;           /* action routine                          */ 
  IntFunc    *call_C;           /* action function                         */ 
  BrActTag    tag;              /* for which window the action is defined  */ 
  struct _BrClass *class;       /* pointer to BrClass in case of open menu */
 } BrAction;                     /*                                         */
                                 /*                                         */
 typedef struct _BrClass {       /*                                         */
   struct _BrClass *next;        /* link to next browsable class            */
   char       *name;             /* unique identifier name                  */
   char       *title;            /* title for popup menu (maybe NULL)       */
   SUBROUTINE *scan_km_F;        /* user function scanning the directory    */
   pCharFunc  *scan_km_C;        /* user function scanning the directory    */
   SUBROUTINE *scan_br_F;        /* user function scanning for browsables   */
   pCharFunc  *scan_br_C;        /* user function scanning for browsables   */
   BrAction   *root;             /* list of actions in root window          */
   BrAction   *open;             /* list of actions in open menu            */
 } BrClass;                      /*                                         */
                                 /*                                         */ 

typedef struct _KmIcon {        /*                                         */ 
  struct _KmIcon *next;         /* link to next icon                       */ 
  char       *name;             /* unique identifier name                  */ 
  int         width;            /* width of the pixmap                     */ 
  int         height;           /* height of the pixmap                    */ 
  char       *bitmap;           /* bitmap data                             */ 
  KmPixmap    pix;              /* filled in Motif part                    */ 
  KmPixmap    hi_pix;           /* high lighted pixmap                     */
 } KmIcon;                       /*                                         */
                                 /*                                         */
 typedef struct _KmClass {       /*                                         */
   struct _KmClass *next;        /* link to next object class               */
   int         is_dir;           /* flag if class has is a directory        */
   char       *name;             /* unique identifier name                  */
   char       *title;            /* title for popup menu (maybe NULL)       */
   char       *big_icon;         /* name of the big icon                    */
   KmIcon     *bicon;            /* pointer to the big icon structure       */
   char       *sm_icon;          /* name of the small icon                  */
   KmIcon     *sicon;            /* pointer to the small icon structure     */
   SUBROUTINE *user_icon_F;      /* user function to return icon bitmap     */
   IntFunc    *user_icon_C;      /* user function to return icon bitmap     */
   BrAction   *cont;             /* list of actions in content window       */
   BrAction   *graf;             /* list of actions in graphics window      */
   int         obj_count;        /* number of objects in content window     */
 } KmClass;                      /*                                         */
                                 /*                                         */ 

typedef enum {                  /*                                         */ 
  KmButtSensitive       = 0x00, /* sensitive button                        */ 
  KmButtNonSensitive    = 0x01, /* non-sensitive button ('NS')             */ 
  KmButtToggleSensitive = 0x02, /* toggle-sensitive button ('TS')          */ 
  KmButtSensitivityMask = 0x03, /* mask for sensitivity type               */ 
  KmButtSeparator       = 0x04, /* put separator in menu ('/')             */ 
  KmButtBrowser         = 0x08  /* button is in main browser ('BR')        */
 } KmButtFlag;                   /*                                         */
                                 /*                                         */
 typedef struct _KmButton {      /*                                         */
   struct _KmButton *next;       /* button label or menu item               */
   char       *menu;             /* menu name or NULL for buttons           */
   char       *label;            /* button label or menu item               */
   SUBROUTINE *call_F;           /* callback routine (FORTRAN)              */
   IntFunc    *call_C;           /* callback routine (C)                    */
   char       *action;           /* name of callback routine                */
   char       *mnemo;            /* button mnemonic                         */
   char       *accel;            /* button accelerator                      */
   char       *accel_text;       /* button accelerator text                 */
   KmButtFlag  flags;            /* sensitivity type etc.                   */
   KmWidget    widget;           /* Motif widget ID                         */
 } KmButton;                     /*                                         */
                                 /*                                         */ 

struct {                        /*                                         */ 
  /* indirect calls to avoid linking HIGZ                                  */ 
  IntFunc    *graf_info_C;      /* pass display, open and close (ixmotif)  */ 
  SUBROUTINE *graf_size_F;      /* resize window (IGRSIZ)                  */ 
  SUBROUTINE *graf_pick_F;      /* identifying graphics objects (IGOBJ)    */ 
  SUBROUTINE *graf_attr_F;      /* set attributes (IGSET)                  */ 
  SUBROUTINE *graf_close_F;     /* close workstation (ICLWK)               */ 
  /* optional routines for Motif customization                             */ 
  pCharFunc  *user_FallBk_C;    /* get application fallbacks               */ 
  IntFunc    *user_TopWid_C;    /* pass toplevel widget identifiers        */
 } klnkaddr;                     /*                                         */ 

typedef enum {                  /*                                         */ 
  KmFLAG_FORGET = 0x01,         /* last value is not kept for Motif panels */ 
  KmFLAG_MINUS  = 0x02,         /* -VALUE is not an abbrev for CHOPT=VALUE */ 
  KmFLAG_QUOTE  = 0x04,         /* do not remove quotes                    */ 
  KmFLAG_VARARG = 0x08,         /* append additional args to this param.   */ 
  KmFLAG_CONST  = 0x10,         /* do not allow to assign a value          */ 
  KmFLAG_HIDDEN = 0x20,         /* do not show in menus                    */ 
  KmFLAG_SEPARATE = 0x40        /* treat arguments as separate tokens      */
 } KmParFlag;                    /*                                         */
                                 /*                                         */
 typedef enum {                  /*                                         */
   KmTYPE_CHAR   = 'C',          /* character string                        */
   KmTYPE_FILE   = 'F',          /* file name                               */
   KmTYPE_INT    = 'I',          /* integer                                 */
   KmTYPE_OPTION = 'O',          /* option                                  */
   KmTYPE_REAL   = 'R'           /* real                                    */
 } KmParType;                    /*                                         */
                                 /*                                         */ 

typedef struct {                /* file name                               */ 
  char         *filter_default; /* filter wildcard                         */ 
  char         *filter_current; /* current filter                          */
 } KmParFile;                    /*                                         */
                                 /*                                         */
 typedef struct {                /*                                         */
   char         *range_lower;    /* lower value of range                    */
   char         *range_upper;    /* upper value of range                    */
   char         *slider_lower;   /* lower limit for slider                  */
   char         *slider_upper;   /* upper limit for slider                  */
   int           decimals;       /* number of decimals used for slider      */
 } KmParInt;                     /*                                         */
                                 /*                                         */
 typedef struct {                /* option                                  */
   char        **text;           /* explanations (parallel to range_value)  */
   int          *mutex;          /* mutex group to which text belongs       */
   int          *radio;          /* radio group to which text belongs       */
 } KmParOption;                  /*                                         */
                                 /*                                         */ 

typedef KmParInt KmParReal;     /* real and int have the same fields       */ 
                                /*                                         */
 typedef struct {                /*                                         */
   char         *name;           /* parameter name                          */
   int           abbrev;         /* minimum length that name is recognized  */
   char         *prompt;         /* prompt string                           */
   char         *dfault;         /* default value                           */
   char         *last;           /* last value for Motif panel (malloced)   */
   int           width;          /* width of input field                    */
   int           range_count;    /* number of items in range_value          */
   char        **range_value;    /* list of allowed values                  */
   int           select_count;   /* number of items in select_count         */
   char        **select_value;   /* list of values for selection box        */
   KmParFlag     flags;          /* special flags                           */
   KmParType     type;           /* parameter type                          */
   void        *ptype;           /* structure pointer selected by type      */
 } KmParameter;                  /*                                         */
                                 /*                                         */ 

typedef struct _KmCommand {     /*					*/   struct _KmCommand *next;	/* link
 to next command			*/   char		*path;		/* command path				*/   char		*name;		/*
 command name				*/   int		hidden;		/* flag if command is invisible		*/  
 int		level;		/* depth of submenus			*/   int		total;		/* total number of
 parameters		*/   int		mandatory;	/* number of mandatory parameters	*/  
 KmParameter	**par;		/* list of total parameter descriptions	*/  
 int		list_par;	/* index+1 of parameter taking a list	*/   int		xcount;		/*
 count number of action calls		*/   SUBROUTINE	*action_F;	/* action
 routine			*/   IntFunc	*action_C;	/* action routine			*/  
 SUBROUTINE	*user_help_F;	/* user help routine			*/  
 pCharFunc	*user_help_C;	/* user help routine			*/   int		nguidance;	/* number
 of lines in guidance text	*/   char		**guidance;	/* help text				*/  
 int		nkeyword;	/* number of lines for keywords		*/   char		**keyword;	/* list
 of keywords			*/   int		nhlink;		/* number of lines for links		*/  
 char		**hlink;	/* list of links			*/   int		argc;		/* number of arguments
 entered		*/   char		**argv;		/* argc argument values			*/  
 char		*argline;	/* argument line as entered		*/   int		*argoffs;	/* argc
 offsets into argline for KUGETE	*/ } KmCommand;			/*					*/ 

typedef struct _KmMenu {        /*                                         */ 
  struct _KmMenu *next;         /* link to next menu                       */ 
  struct _KmMenu *down;         /* link to submenu                         */ 
  char         *path;           /* path of parent menu                     */ 
  char         *name;           /* menu name                               */ 
  int           level;          /* depth of submenus                       */ 
  KmCommand    *cmds;           /* link to first command                   */ 
  int          nguidance;       /* number of lines in guidance text        */ 
  char        **guidance;       /* help text                               */ 
  int          nkeyword;        /* number of lines for keywords            */ 
  char        **keyword;        /* list of keywords                        */ 
  int          nhlink;          /* number of lines for links               */ 
  char        **hlink;          /* list of links                           */
 } KmMenu;                       /*                                         */
                                 /*                                         */
 extern void klnkbrcl();         /*                                         */
 extern void klnkicon();         /*                                         */
 extern void klnkkmcl();         /*                                         */
 extern void klnkmenu();         /*                                         */
                                 /*                                         */ 

#ifdef F77_LCASE
#  define guinti_ guinti
#  define omxdraw_ omxdraw
#  define omxcntr_ omxcntr
#  define omxcntr1_ omxcntr1
#  define omxplot_ omxplot
#endif

#ifdef F77_UCASE
#  define guinti_ GUINTI
#  define omxdraw_ OMXDRAW
#  define omxcntr_ OMXCNTR
#  define omxcntr1_ OMXCNTR1
#  define omxplot_ OMXPLOT
#endif

#ifdef IBM370
#  pragma linkage(GUINTI,FORTRAN)
#  pragma linkage(OMXDRAW,FORTRAN)
#  pragma linkage(OMXCNTR,FORTRAN)
#  pragma linkage(OMXCNTR1,FORTRAN)
#  pragma linkage(OMXPLOT,FORTRAN)
#endif

extern void type_of_call guinti_();
extern void type_of_call omxdraw_();
extern void type_of_call omxcntr_();
extern void type_of_call omxcntr1_();
extern void type_of_call omxplot_();

void type_of_call guinti_()
{

static KmParReal   _OMGEANT_DRAW_ITX_X_type = { (char*)0, (char*)0, (char*)0,
 (char*)0, 0 };
static KmParameter _OMGEANT_DRAW_ITX_X = { "X", 1, "X - coordinate", "10.",
 (char*)0, 12, 0, (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_REAL,
 &_OMGEANT_DRAW_ITX_X_type };
static KmParReal   _OMGEANT_DRAW_ITX_Y_type = { (char*)0, (char*)0, (char*)0,
 (char*)0, 0 };
static KmParameter _OMGEANT_DRAW_ITX_Y = { "Y", 1, "Y - coordinate", "10.",
 (char*)0, 12, 0, (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_REAL,
 &_OMGEANT_DRAW_ITX_Y_type };
static KmParameter _OMGEANT_DRAW_ITX_TEXT = { "TEXT", 4, "Text to be drawn",
 " ", (char*)0, 20, 0, (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_CHAR, 
 (void*)0 };
static KmParameter *_OMGEANT_DRAW_ITX_parameters[] = { &_OMGEANT_DRAW_ITX_X,
 &_OMGEANT_DRAW_ITX_Y, &_OMGEANT_DRAW_ITX_TEXT };
static char *_OMGEANT_DRAW_ITX_guidance[] = { "Draw a text (ITX X Y text)" };
static KmCommand _OMGEANT_DRAW_ITX = {  (KmCommand*)0, "/OMGEANT/DRAW/ITX",
 "ITX", 0, 2, 3, 3, _OMGEANT_DRAW_ITX_parameters, 0, 0, omxdraw_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_DRAW_ITX_guidance, 0, (char**)0,
 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_DRAW_SPARATT_IPAR_type = { "1", "8", "1", "8", 0 };
static KmParameter _OMGEANT_DRAW_SPARATT_IPAR = { "IPAR", 4,
 "Particle number", (char*)0, (char*)0, 2, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_DRAW_SPARATT_IPAR_type };
static KmParInt    _OMGEANT_DRAW_SPARATT_MODE_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_DRAW_SPARATT_MODE = { "MODE", 4,
 "Mode of the line (=0 - skip these particles)", (char*)0, (char*)0, 8, 0,
 (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_INT,
 &_OMGEANT_DRAW_SPARATT_MODE_type };
static KmParInt    _OMGEANT_DRAW_SPARATT_COLOR_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_DRAW_SPARATT_COLOR = { "COLOR", 5,
 "Color of the line", (char*)0, (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_DRAW_SPARATT_COLOR_type };
static KmParameter *_OMGEANT_DRAW_SPARATT_parameters[] = {
 &_OMGEANT_DRAW_SPARATT_IPAR, &_OMGEANT_DRAW_SPARATT_MODE,
 &_OMGEANT_DRAW_SPARATT_COLOR };
static char *_OMGEANT_DRAW_SPARATT_guidance[] = {
 "Set the line mode and color for drawing trajectories of different\
 particles",
 "          ITRTYP  PARTICLE  | mode | color |       HIGZ         |",
 "          -------------------------------------------------------",
 "              1   gammas    |  3   |  4    | dotted      blue   |",
 "              2   electrons |  1   |  2    | solid       red    |",
 "              3   neutral   |  4   |  1    | dot-dashed  black  |",
 "              4   hadrons   |  1   |  2    | solid       red    |",
 "              5   muons     |  2   |  3    | dashed      green  |",
 "              6   geantino  |  1   |  1    | dot-dashed  black  |",
 "              7   cerenkov  |  3   |  6    | dotted     magenta |" };
static KmCommand _OMGEANT_DRAW_SPARATT = { &_OMGEANT_DRAW_ITX,
 "/OMGEANT/DRAW/SPARATT", "SPARATT", 0, 2, 3, 0,
 _OMGEANT_DRAW_SPARATT_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 10, _OMGEANT_DRAW_SPARATT_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParameter _OMGEANT_DRAW_DDIGI_IUSET = { "IUSET", 5,
 "Name of the detector SET", "*   ", (char*)0, 20, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_CHAR,  (void*)0 };
static KmParameter _OMGEANT_DRAW_DDIGI_IUDET = { "IUDET", 5,
 "Name of the detector", "*   ", (char*)0, 20, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_CHAR,  (void*)0 };
static KmParInt    _OMGEANT_DRAW_DDIGI_IUNI_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_DRAW_DDIGI_IUNI = { "IUNI", 4,
 "Number of the unit", "0", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_DRAW_DDIGI_IUNI_type };
static KmParameter *_OMGEANT_DRAW_DDIGI_parameters[] = {
 &_OMGEANT_DRAW_DDIGI_IUSET, &_OMGEANT_DRAW_DDIGI_IUDET,
 &_OMGEANT_DRAW_DDIGI_IUNI };
static char *_OMGEANT_DRAW_DDIGI_guidance[] = {
 "Plots the digitisations in wire chambers (DDIGI [set] [det] [unit])" };
static KmCommand _OMGEANT_DRAW_DDIGI = { &_OMGEANT_DRAW_SPARATT,
 "/OMGEANT/DRAW/DDIGI", "DDIGI", 0, 2, 3, 0, _OMGEANT_DRAW_DDIGI_parameters,
 0, 0, omxdraw_, (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 1,
 _OMGEANT_DRAW_DDIGI_guidance, 0, (char**)0, 0, (char**)0, 0, (char**)0,
 (char*)0, (int*)0 };

static KmParInt    _OMGEANT_CONTROL_GETSEED_EVENT_type = { "1", "999999999",
 "1", "999999999", 0 };
static KmParameter _OMGEANT_CONTROL_GETSEED_EVENT = { "EVENT", 5,
 " serial event (entry) number in the file ", "0", (char*)0, 10, 0, (char**)0,
 0, (char**)0, (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_GETSEED_EVENT_type
 };
static KmParInt    _OMGEANT_CONTROL_GETSEED_IPRI_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_GETSEED_IPRI = { "IPRI", 4,
 " <>0 - print the seed values ", "0", (char*)0, 8, 0, (char**)0, 0,
 (char**)0, (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_GETSEED_IPRI_type };
static KmParameter _OMGEANT_CONTROL_GETSEED_NAME = { "NAME", 4,
 " filename (up to 80 characters)", "none", (char*)0, 20, 0, (char**)0, 0,
 (char**)0, (KmParFlag)0, KmTYPE_CHAR,  (void*)0 };
static KmParameter *_OMGEANT_CONTROL_GETSEED_parameters[] = {
 &_OMGEANT_CONTROL_GETSEED_EVENT, &_OMGEANT_CONTROL_GETSEED_IPRI,
 &_OMGEANT_CONTROL_GETSEED_NAME };
static char *_OMGEANT_CONTROL_GETSEED_guidance[] = {
 "  Reads a set of random generator seeds to re-generate a particular event.",
 "  One has to define the filename (direct access unformatted file, written by\
 COMGEANT,", "  and the serial event (entry) number." };
static KmCommand _OMGEANT_CONTROL_GETSEED = {  (KmCommand*)0,
 "/OMGEANT/CONTROL/GETSEED", "GETSEED", 0, 2, 3, 3,
 _OMGEANT_CONTROL_GETSEED_parameters, 0, 0, omxcntr1_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 3, _OMGEANT_CONTROL_GETSEED_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static char *_OMGEANT_CONTROL_NTICLOSE_guidance[] = {
 "  Close the input NTUPLE" };
static KmCommand _OMGEANT_CONTROL_NTICLOSE = { &_OMGEANT_CONTROL_GETSEED,
 "/OMGEANT/CONTROL/NTICLOSE", "NTICLOSE", 0, 2, 0, 0, (KmParameter**)0, 0, 0,
 omxcntr_, (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 1,
 _OMGEANT_CONTROL_NTICLOSE_guidance, 0, (char**)0, 0, (char**)0, 0, (char**)0,
 (char*)0, (int*)0 };

static char *_OMGEANT_CONTROL_NTIOPEN_guidance[] = {
 "  Opens the input NTUPLE: see NTIPROC" };
static KmCommand _OMGEANT_CONTROL_NTIOPEN = { &_OMGEANT_CONTROL_NTICLOSE,
 "/OMGEANT/CONTROL/NTIOPEN", "NTIOPEN", 0, 2, 0, 0, (KmParameter**)0, 0, 0,
 omxcntr_, (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 1,
 _OMGEANT_CONTROL_NTIOPEN_guidance, 0, (char**)0, 0, (char**)0, 0, (char**)0,
 (char*)0, (int*)0 };

static KmParInt    _OMGEANT_CONTROL_NTIPROC_BEAM_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_NTIPROC_BEAM = { "BEAM", 4,
 "!=0 - read the beam ntuple  ", "0", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_NTIPROC_BEAM_type };
static KmParInt    _OMGEANT_CONTROL_NTIPROC_KINE_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_NTIPROC_KINE = { "KINE", 4,
 "!=0 - read the kinematics ntuple  ", "0", (char*)0, 8, 0, (char**)0, 0,
 (char**)0, (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_NTIPROC_KINE_type };
static KmParInt    _OMGEANT_CONTROL_NTIPROC_HITS_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_NTIPROC_HITS = { "HITS", 4,
 "!=0 - read the hits ntuple  ", "0", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_NTIPROC_HITS_type };
static KmParInt    _OMGEANT_CONTROL_NTIPROC_LUND_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_NTIPROC_LUND = { "LUND", 4,
 "!=0 - read the LUND ntuple  ", "0", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_NTIPROC_LUND_type };
static KmParameter *_OMGEANT_CONTROL_NTIPROC_parameters[] = {
 &_OMGEANT_CONTROL_NTIPROC_BEAM, &_OMGEANT_CONTROL_NTIPROC_KINE,
 &_OMGEANT_CONTROL_NTIPROC_HITS, &_OMGEANT_CONTROL_NTIPROC_LUND };
static char *_OMGEANT_CONTROL_NTIPROC_guidance[] = {
 "  LUND=1   - instead of simulating a LUND event - take it from the NTUPLE" };
static KmCommand _OMGEANT_CONTROL_NTIPROC = { &_OMGEANT_CONTROL_NTIOPEN,
 "/OMGEANT/CONTROL/NTIPROC", "NTIPROC", 0, 2, 4, 0,
 _OMGEANT_CONTROL_NTIPROC_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_CONTROL_NTIPROC_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static char *_OMGEANT_CONTROL_NTOCLOSE_guidance[] = {
 "  Close the output NTUPLE" };
static KmCommand _OMGEANT_CONTROL_NTOCLOSE = { &_OMGEANT_CONTROL_NTIPROC,
 "/OMGEANT/CONTROL/NTOCLOSE", "NTOCLOSE", 0, 2, 0, 0, (KmParameter**)0, 0, 0,
 omxcntr_, (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 1,
 _OMGEANT_CONTROL_NTOCLOSE_guidance, 0, (char**)0, 0, (char**)0, 0, (char**)0,
 (char*)0, (int*)0 };

static char *_OMGEANT_CONTROL_NTOOPEN_guidance[] = {
 "  Opens the output NTUPLE: see NTOPROC" };
static KmCommand _OMGEANT_CONTROL_NTOOPEN = { &_OMGEANT_CONTROL_NTOCLOSE,
 "/OMGEANT/CONTROL/NTOOPEN", "NTOOPEN", 0, 2, 0, 0, (KmParameter**)0, 0, 0,
 omxcntr_, (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 1,
 _OMGEANT_CONTROL_NTOOPEN_guidance, 0, (char**)0, 0, (char**)0, 0, (char**)0,
 (char*)0, (int*)0 };

static KmParInt    _OMGEANT_CONTROL_NTOPROC_BEAM_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_NTOPROC_BEAM = { "BEAM", 4,
 "!=0 - fill the beam ntuple  ", "0", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_NTOPROC_BEAM_type };
static KmParInt    _OMGEANT_CONTROL_NTOPROC_KINE_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_NTOPROC_KINE = { "KINE", 4,
 "!=0 - fill the kinematics ntuple  ", "0", (char*)0, 8, 0, (char**)0, 0,
 (char**)0, (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_NTOPROC_KINE_type };
static KmParInt    _OMGEANT_CONTROL_NTOPROC_HITS_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_NTOPROC_HITS = { "HITS", 4,
 "!=0 - fill the hits ntuple  ", "0", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_NTOPROC_HITS_type };
static KmParameter *_OMGEANT_CONTROL_NTOPROC_parameters[] = {
 &_OMGEANT_CONTROL_NTOPROC_BEAM, &_OMGEANT_CONTROL_NTOPROC_KINE,
 &_OMGEANT_CONTROL_NTOPROC_HITS };
static char *_OMGEANT_CONTROL_NTOPROC_guidance[] = {
 "  KINE=-1  - write all the vertices and tracks",
 "  KINE=-2  - write only the vertex #1 and the tracks stemming from it",
 "  KINE=n>0 - write only the track #n and all descendent tracks and verices"
 };
static KmCommand _OMGEANT_CONTROL_NTOPROC = { &_OMGEANT_CONTROL_NTOOPEN,
 "/OMGEANT/CONTROL/NTOPROC", "NTOPROC", 0, 2, 3, 0,
 _OMGEANT_CONTROL_NTOPROC_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 3, _OMGEANT_CONTROL_NTOPROC_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static char *_OMGEANT_CONTROL_PHYGET_guidance[] = {
 "Read a PHYNIX event (/PHTRAC/) from LUN=21" };
static KmCommand _OMGEANT_CONTROL_PHYGET = { &_OMGEANT_CONTROL_NTOPROC,
 "/OMGEANT/CONTROL/PHYGET", "PHYGET", 0, 2, 0, 0, (KmParameter**)0, 0, 0,
 omxcntr_, (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 1,
 _OMGEANT_CONTROL_PHYGET_guidance, 0, (char**)0, 0, (char**)0, 0, (char**)0,
 (char*)0, (int*)0 };

static KmParInt    _OMGEANT_CONTROL_OPLUND_IFLA_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_OPLUND_IFLA = { "IFLA", 4,
 "flag for LULIST", "1", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_OPLUND_IFLA_type };
static KmParameter *_OMGEANT_CONTROL_OPLUND_parameters[] = {
 &_OMGEANT_CONTROL_OPLUND_IFLA };
static char *_OMGEANT_CONTROL_OPLUND_guidance[] = {
 "Prints the LUND structure using LULIST(ifla) (OPLUND [ifla])" };
static KmCommand _OMGEANT_CONTROL_OPLUND = { &_OMGEANT_CONTROL_PHYGET,
 "/OMGEANT/CONTROL/OPLUND", "OPLUND", 0, 2, 1, 0,
 _OMGEANT_CONTROL_OPLUND_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_CONTROL_OPLUND_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_CONTROL_OPTRIG_IFLA_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_OPTRIG_IFLA = { "IFLA", 4,
 "Flag (not used at the moment) ", "0", (char*)0, 8, 0, (char**)0, 0,
 (char**)0, (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_OPTRIG_IFLA_type };
static KmParameter *_OMGEANT_CONTROL_OPTRIG_parameters[] = {
 &_OMGEANT_CONTROL_OPTRIG_IFLA };
static char *_OMGEANT_CONTROL_OPTRIG_guidance[] = {
 "Prints the trigger detectors hits (OPTRIG [ifla])" };
static KmCommand _OMGEANT_CONTROL_OPTRIG = { &_OMGEANT_CONTROL_OPLUND,
 "/OMGEANT/CONTROL/OPTRIG", "OPTRIG", 0, 2, 1, 0,
 _OMGEANT_CONTROL_OPTRIG_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_CONTROL_OPTRIG_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_CONTROL_OPOHIT_ITRA_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_OPOHIT_ITRA = { "ITRA", 4,
 "Track number, =0 - all", "0", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_OPOHIT_ITRA_type };
static KmParameter *_OMGEANT_CONTROL_OPOHIT_parameters[] = {
 &_OMGEANT_CONTROL_OPOHIT_ITRA };
static char *_OMGEANT_CONTROL_OPOHIT_guidance[] = {
 "Prints local hit bank (OPOHIT [itra])" };
static KmCommand _OMGEANT_CONTROL_OPOHIT = { &_OMGEANT_CONTROL_OPTRIG,
 "/OMGEANT/CONTROL/OPOHIT", "OPOHIT", 0, 2, 1, 0,
 _OMGEANT_CONTROL_OPOHIT_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_CONTROL_OPOHIT_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParameter _OMGEANT_CONTROL_OPDIGI_IUSET = { "IUSET", 5,
 "Name of the detector SET", "*   ", (char*)0, 20, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_CHAR,  (void*)0 };
static KmParameter _OMGEANT_CONTROL_OPDIGI_IUDET = { "IUDET", 5,
 "Name of the detector", "*   ", (char*)0, 20, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_CHAR,  (void*)0 };
static KmParInt    _OMGEANT_CONTROL_OPDIGI_ITRA_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_OPDIGI_ITRA = { "ITRA", 4,
 "Track number, =0 - all", "0", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_OPDIGI_ITRA_type };
static KmParameter _OMGEANT_CONTROL_OPDIGI_OPT = { "OPT", 3,
 "Option: what to print", " ", (char*)0, 20, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_CHAR,  (void*)0 };
static KmParameter *_OMGEANT_CONTROL_OPDIGI_parameters[] = {
 &_OMGEANT_CONTROL_OPDIGI_IUSET, &_OMGEANT_CONTROL_OPDIGI_IUDET,
 &_OMGEANT_CONTROL_OPDIGI_ITRA, &_OMGEANT_CONTROL_OPDIGI_OPT };
static char *_OMGEANT_CONTROL_OPDIGI_guidance[] = {
 "Prints digitizings (OPDIGI [set] [det] [itra] [opt] )",
 "       OPT=' ' - call GEANT routine GPDIGI (all tracks)",
 "           'G' - prints GEANT banks from OMGEANT",
 "           'O' - prints OMGEANT banks (all detectors)" };
static KmCommand _OMGEANT_CONTROL_OPDIGI = { &_OMGEANT_CONTROL_OPOHIT,
 "/OMGEANT/CONTROL/OPDIGI", "OPDIGI", 0, 2, 4, 0,
 _OMGEANT_CONTROL_OPDIGI_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 4, _OMGEANT_CONTROL_OPDIGI_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParameter _OMGEANT_CONTROL_OPHITS_IUSET = { "IUSET", 5,
 "Name of the detector SET", "*   ", (char*)0, 20, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_CHAR,  (void*)0 };
static KmParameter _OMGEANT_CONTROL_OPHITS_IUDET = { "IUDET", 5,
 "Name of the detector", "*   ", (char*)0, 20, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_CHAR,  (void*)0 };
static KmParInt    _OMGEANT_CONTROL_OPHITS_ITRA_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_OPHITS_ITRA = { "ITRA", 4,
 "Track number, =0 - all", "0", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_OPHITS_ITRA_type };
static KmParameter _OMGEANT_CONTROL_OPHITS_OPT = { "OPT", 3,
 "Option: what to print", " ", (char*)0, 20, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_CHAR,  (void*)0 };
static KmParameter *_OMGEANT_CONTROL_OPHITS_parameters[] = {
 &_OMGEANT_CONTROL_OPHITS_IUSET, &_OMGEANT_CONTROL_OPHITS_IUDET,
 &_OMGEANT_CONTROL_OPHITS_ITRA, &_OMGEANT_CONTROL_OPHITS_OPT };
static char *_OMGEANT_CONTROL_OPHITS_guidance[] = {
 "Prints hits (OPHITS [set] [det] [itra] [opt])",
 "       OPT=' ' - call GEANT routine GPHITS (all tracks)",
 "           'D' - prints GEANT banks from OMGEANT, include the reference",
 "                 to digitisations" };
static KmCommand _OMGEANT_CONTROL_OPHITS = { &_OMGEANT_CONTROL_OPDIGI,
 "/OMGEANT/CONTROL/OPHITS", "OPHITS", 0, 2, 4, 0,
 _OMGEANT_CONTROL_OPHITS_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 4, _OMGEANT_CONTROL_OPHITS_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_CONTROL_OPRIEV_IFLAG_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_OPRIEV_IFLAG = { "IFLAG", 5,
 "Flag - what to print", "0", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_OPRIEV_IFLAG_type };
static KmParReal   _OMGEANT_CONTROL_OPRIEV_ECUT_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_OPRIEV_ECUT = { "ECUT", 4,
 "Cut on the energy", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_OPRIEV_ECUT_type };
static KmParameter *_OMGEANT_CONTROL_OPRIEV_parameters[] = {
 &_OMGEANT_CONTROL_OPRIEV_IFLAG, &_OMGEANT_CONTROL_OPRIEV_ECUT };
static char *_OMGEANT_CONTROL_OPRIEV_guidance[] = {
 "Prints the event data (OMPRIEV [iflag] [cut])",
 "           iflag=0 - the header only",
 "                =1 - list of tracks with Ekin>ECUT" };
static KmCommand _OMGEANT_CONTROL_OPRIEV = { &_OMGEANT_CONTROL_OPHITS,
 "/OMGEANT/CONTROL/OPRIEV", "OPRIEV", 0, 2, 2, 0,
 _OMGEANT_CONTROL_OPRIEV_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 3, _OMGEANT_CONTROL_OPRIEV_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_CONTROL_OPRIPA_IPAR_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_OPRIPA_IPAR = { "IPAR", 4,
 "the particle number, =0 - all", "0", (char*)0, 8, 0, (char**)0, 0,
 (char**)0, (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_OPRIPA_IPAR_type };
static KmParameter *_OMGEANT_CONTROL_OPRIPA_parameters[] = {
 &_OMGEANT_CONTROL_OPRIPA_IPAR };
static char *_OMGEANT_CONTROL_OPRIPA_guidance[] = {
 "Prints the particle data (OMPRIPA [ipar])" };
static KmCommand _OMGEANT_CONTROL_OPRIPA = { &_OMGEANT_CONTROL_OPRIEV,
 "/OMGEANT/CONTROL/OPRIPA", "OPRIPA", 0, 2, 1, 0,
 _OMGEANT_CONTROL_OPRIPA_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_CONTROL_OPRIPA_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParameter _OMGEANT_CONTROL_OPDET_IUSET = { "IUSET", 5,
 "Name of the detector SET", "*   ", (char*)0, 20, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_CHAR,  (void*)0 };
static KmParameter _OMGEANT_CONTROL_OPDET_IUDET = { "IUDET", 5,
 "Name of the detector", "*   ", (char*)0, 20, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_CHAR,  (void*)0 };
static KmParameter *_OMGEANT_CONTROL_OPDET_parameters[] = {
 &_OMGEANT_CONTROL_OPDET_IUSET, &_OMGEANT_CONTROL_OPDET_IUDET };
static char *_OMGEANT_CONTROL_OPDET_guidance[] = {
 "Prints user information on detectors (OPDET [set] [det])" };
static KmCommand _OMGEANT_CONTROL_OPDET = { &_OMGEANT_CONTROL_OPRIPA,
 "/OMGEANT/CONTROL/OPDET", "OPDET", 0, 2, 2, 0,
 _OMGEANT_CONTROL_OPDET_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_CONTROL_OPDET_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_CONTROL_TKINE5_tkin1_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE5_tkin1 = { "tkin1", 5,
 "Type of simulated particle ", "8", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_TKINE5_tkin1_type };
static KmParInt    _OMGEANT_CONTROL_TKINE5_tkin2_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE5_tkin2 = { "tkin2", 5,
 "Number of simulated particles of this type", "1", (char*)0, 8, 0, (char**)0,
 0, (char**)0, (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_TKINE5_tkin2_type };
static KmParReal   _OMGEANT_CONTROL_TKINE5_tkin3_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE5_tkin3 = { "tkin3", 5,
 "P minimum /GeV ", "1.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE5_tkin3_type };
static KmParReal   _OMGEANT_CONTROL_TKINE5_tkin4_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE5_tkin4 = { "tkin4", 5,
 "P maximum /GeV ", "100.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE5_tkin4_type };
static KmParReal   _OMGEANT_CONTROL_TKINE5_tkin5_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE5_tkin5 = { "tkin5", 5,
 "Pt mean /GeV ", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE5_tkin5_type };
static KmParameter *_OMGEANT_CONTROL_TKINE5_parameters[] = {
 &_OMGEANT_CONTROL_TKINE5_tkin1, &_OMGEANT_CONTROL_TKINE5_tkin2,
 &_OMGEANT_CONTROL_TKINE5_tkin3, &_OMGEANT_CONTROL_TKINE5_tkin4,
 &_OMGEANT_CONTROL_TKINE5_tkin5 };
static char *_OMGEANT_CONTROL_TKINE5_guidance[] = {
 " Parameters of 5-th class of particles to simulate" };
static KmCommand _OMGEANT_CONTROL_TKINE5 = { &_OMGEANT_CONTROL_OPDET,
 "/OMGEANT/CONTROL/TKINE5", "TKINE5", 0, 2, 5, 5,
 _OMGEANT_CONTROL_TKINE5_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_CONTROL_TKINE5_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_CONTROL_TKINE4_tkin1_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE4_tkin1 = { "tkin1", 5,
 "Type of simulated particle ", "8", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_TKINE4_tkin1_type };
static KmParInt    _OMGEANT_CONTROL_TKINE4_tkin2_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE4_tkin2 = { "tkin2", 5,
 "Number of simulated particles of this type", "1", (char*)0, 8, 0, (char**)0,
 0, (char**)0, (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_TKINE4_tkin2_type };
static KmParReal   _OMGEANT_CONTROL_TKINE4_tkin3_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE4_tkin3 = { "tkin3", 5,
 "P minimum /GeV ", "1.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE4_tkin3_type };
static KmParReal   _OMGEANT_CONTROL_TKINE4_tkin4_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE4_tkin4 = { "tkin4", 5,
 "P maximum /GeV ", "100.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE4_tkin4_type };
static KmParReal   _OMGEANT_CONTROL_TKINE4_tkin5_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE4_tkin5 = { "tkin5", 5,
 "Pt mean /GeV ", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE4_tkin5_type };
static KmParameter *_OMGEANT_CONTROL_TKINE4_parameters[] = {
 &_OMGEANT_CONTROL_TKINE4_tkin1, &_OMGEANT_CONTROL_TKINE4_tkin2,
 &_OMGEANT_CONTROL_TKINE4_tkin3, &_OMGEANT_CONTROL_TKINE4_tkin4,
 &_OMGEANT_CONTROL_TKINE4_tkin5 };
static char *_OMGEANT_CONTROL_TKINE4_guidance[] = {
 " Parameters of 4-th class of particles to simulate" };
static KmCommand _OMGEANT_CONTROL_TKINE4 = { &_OMGEANT_CONTROL_TKINE5,
 "/OMGEANT/CONTROL/TKINE4", "TKINE4", 0, 2, 5, 5,
 _OMGEANT_CONTROL_TKINE4_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_CONTROL_TKINE4_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_CONTROL_TKINE3_tkin1_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE3_tkin1 = { "tkin1", 5,
 "Type of simulated particle ", "8", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_TKINE3_tkin1_type };
static KmParInt    _OMGEANT_CONTROL_TKINE3_tkin2_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE3_tkin2 = { "tkin2", 5,
 "Number of simulated particles of this type", "1", (char*)0, 8, 0, (char**)0,
 0, (char**)0, (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_TKINE3_tkin2_type };
static KmParReal   _OMGEANT_CONTROL_TKINE3_tkin3_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE3_tkin3 = { "tkin3", 5,
 "P minimum /GeV ", "1.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE3_tkin3_type };
static KmParReal   _OMGEANT_CONTROL_TKINE3_tkin4_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE3_tkin4 = { "tkin4", 5,
 "P maximum /GeV ", "100.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE3_tkin4_type };
static KmParReal   _OMGEANT_CONTROL_TKINE3_tkin5_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE3_tkin5 = { "tkin5", 5,
 "Pt mean /GeV ", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE3_tkin5_type };
static KmParameter *_OMGEANT_CONTROL_TKINE3_parameters[] = {
 &_OMGEANT_CONTROL_TKINE3_tkin1, &_OMGEANT_CONTROL_TKINE3_tkin2,
 &_OMGEANT_CONTROL_TKINE3_tkin3, &_OMGEANT_CONTROL_TKINE3_tkin4,
 &_OMGEANT_CONTROL_TKINE3_tkin5 };
static char *_OMGEANT_CONTROL_TKINE3_guidance[] = {
 " Parameters of 3-rd class of particles to simulate" };
static KmCommand _OMGEANT_CONTROL_TKINE3 = { &_OMGEANT_CONTROL_TKINE4,
 "/OMGEANT/CONTROL/TKINE3", "TKINE3", 0, 2, 5, 5,
 _OMGEANT_CONTROL_TKINE3_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_CONTROL_TKINE3_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_CONTROL_TKINE2_tkin1_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE2_tkin1 = { "tkin1", 5,
 "Type of simulated particle ", "8", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_TKINE2_tkin1_type };
static KmParInt    _OMGEANT_CONTROL_TKINE2_tkin2_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE2_tkin2 = { "tkin2", 5,
 "Number of simulated particles of this type", "1", (char*)0, 8, 0, (char**)0,
 0, (char**)0, (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_TKINE2_tkin2_type };
static KmParReal   _OMGEANT_CONTROL_TKINE2_tkin3_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE2_tkin3 = { "tkin3", 5,
 "P minimum /GeV ", "1.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE2_tkin3_type };
static KmParReal   _OMGEANT_CONTROL_TKINE2_tkin4_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE2_tkin4 = { "tkin4", 5,
 "P maximum /GeV ", "100.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE2_tkin4_type };
static KmParReal   _OMGEANT_CONTROL_TKINE2_tkin5_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE2_tkin5 = { "tkin5", 5,
 "Pt mean /GeV ", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE2_tkin5_type };
static KmParameter *_OMGEANT_CONTROL_TKINE2_parameters[] = {
 &_OMGEANT_CONTROL_TKINE2_tkin1, &_OMGEANT_CONTROL_TKINE2_tkin2,
 &_OMGEANT_CONTROL_TKINE2_tkin3, &_OMGEANT_CONTROL_TKINE2_tkin4,
 &_OMGEANT_CONTROL_TKINE2_tkin5 };
static char *_OMGEANT_CONTROL_TKINE2_guidance[] = {
 " Parameters of 2-nd class of particles to simulate" };
static KmCommand _OMGEANT_CONTROL_TKINE2 = { &_OMGEANT_CONTROL_TKINE3,
 "/OMGEANT/CONTROL/TKINE2", "TKINE2", 0, 2, 5, 5,
 _OMGEANT_CONTROL_TKINE2_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_CONTROL_TKINE2_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_CONTROL_TKINE1_tkin1_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE1_tkin1 = { "tkin1", 5,
 "Type of simulated particle ", "8", (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_TKINE1_tkin1_type };
static KmParInt    _OMGEANT_CONTROL_TKINE1_tkin2_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE1_tkin2 = { "tkin2", 5,
 "Number of simulated particles of this type", "1", (char*)0, 8, 0, (char**)0,
 0, (char**)0, (KmParFlag)0, KmTYPE_INT, &_OMGEANT_CONTROL_TKINE1_tkin2_type };
static KmParReal   _OMGEANT_CONTROL_TKINE1_tkin3_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE1_tkin3 = { "tkin3", 5,
 "P minimum /GeV ", "1.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE1_tkin3_type };
static KmParReal   _OMGEANT_CONTROL_TKINE1_tkin4_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE1_tkin4 = { "tkin4", 5,
 "P maximum /GeV ", "100.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE1_tkin4_type };
static KmParReal   _OMGEANT_CONTROL_TKINE1_tkin5_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_CONTROL_TKINE1_tkin5 = { "tkin5", 5,
 "Pt mean /GeV ", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_CONTROL_TKINE1_tkin5_type };
static KmParameter *_OMGEANT_CONTROL_TKINE1_parameters[] = {
 &_OMGEANT_CONTROL_TKINE1_tkin1, &_OMGEANT_CONTROL_TKINE1_tkin2,
 &_OMGEANT_CONTROL_TKINE1_tkin3, &_OMGEANT_CONTROL_TKINE1_tkin4,
 &_OMGEANT_CONTROL_TKINE1_tkin5 };
static char *_OMGEANT_CONTROL_TKINE1_guidance[] = {
 " Parameters of 1-st class of particles to simulate" };
static KmCommand _OMGEANT_CONTROL_TKINE1 = { &_OMGEANT_CONTROL_TKINE2,
 "/OMGEANT/CONTROL/TKINE1", "TKINE1", 0, 2, 5, 5,
 _OMGEANT_CONTROL_TKINE1_parameters, 0, 0, omxcntr_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_CONTROL_TKINE1_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_OPLOT_PDEVIATION_IDT_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PDEVIATION_IDT = { "IDT", 3,
 "IDTRID identifier of the plane ", (char*)0, (char*)0, 8, 0, (char**)0, 0,
 (char**)0, (KmParFlag)0, KmTYPE_INT, &_OMGEANT_OPLOT_PDEVIATION_IDT_type };
static KmParInt    _OMGEANT_OPLOT_PDEVIATION_ID1_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PDEVIATION_ID1 = { "ID1", 3,
 "ID of the histogram for slope deviations. Should be booked ", (char*)0,
 (char*)0, 8, 0, (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_INT,
 &_OMGEANT_OPLOT_PDEVIATION_ID1_type };
static KmParInt    _OMGEANT_OPLOT_PDEVIATION_ID2_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PDEVIATION_ID2 = { "ID2", 3,
 "ID of the histogram for position deviations.", (char*)0, (char*)0, 8, 0,
 (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_INT,
 &_OMGEANT_OPLOT_PDEVIATION_ID2_type };
static KmParInt    _OMGEANT_OPLOT_PDEVIATION_ID3_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PDEVIATION_ID3 = { "ID3", 3,
 "ID of the 2-dim histogram for slope-position deviations.", (char*)0,
 (char*)0, 8, 0, (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_INT,
 &_OMGEANT_OPLOT_PDEVIATION_ID3_type };
static KmParameter *_OMGEANT_OPLOT_PDEVIATION_parameters[] = {
 &_OMGEANT_OPLOT_PDEVIATION_IDT, &_OMGEANT_OPLOT_PDEVIATION_ID1,
 &_OMGEANT_OPLOT_PDEVIATION_ID2, &_OMGEANT_OPLOT_PDEVIATION_ID3 };
static char *_OMGEANT_OPLOT_PDEVIATION_guidance[] = {
 "  Fills histograms with track deviation from a straight line",
 "  measured at the exit from a specified detector" };
static KmCommand _OMGEANT_OPLOT_PDEVIATION = {  (KmCommand*)0,
 "/OMGEANT/OPLOT/PDEVIATION", "PDEVIATION", 0, 2, 4, 4,
 _OMGEANT_OPLOT_PDEVIATION_parameters, 0, 0, omxplot_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 2, _OMGEANT_OPLOT_PDEVIATION_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_OPLOT_PSCATRAJ_ID_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PSCATRAJ_ID = { "ID", 2,
 "ID of the histogram. Should be booked ", (char*)0, (char*)0, 8, 0,
 (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_INT,
 &_OMGEANT_OPLOT_PSCATRAJ_ID_type };
static KmParInt    _OMGEANT_OPLOT_PSCATRAJ_PARA_type = { "0", "1", "0", "1", 0
 };
static KmParameter _OMGEANT_OPLOT_PSCATRAJ_PARA = { "PARA", 4,
 "Type of the value histogrammed: 0 - RL, 1 - Int.len.", "0", (char*)0, 2, 0,
 (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_INT,
 &_OMGEANT_OPLOT_PSCATRAJ_PARA_type };
static KmParInt    _OMGEANT_OPLOT_PSCATRAJ_TYPE_type = { "1", "20", "1", "20",
 0 };
static KmParameter _OMGEANT_OPLOT_PSCATRAJ_TYPE = { "TYPE", 4,
 "Particle type", "14", (char*)0, 3, 0, (char**)0, 0, (char**)0, (KmParFlag)0,
 KmTYPE_INT, &_OMGEANT_OPLOT_PSCATRAJ_TYPE_type };
static KmParReal   _OMGEANT_OPLOT_PSCATRAJ_X_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PSCATRAJ_X = { "X", 1,
 "X-coordinate of the track start", "0.", (char*)0, 12, 0, (char**)0, 0,
 (char**)0, (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_OPLOT_PSCATRAJ_X_type };
static KmParReal   _OMGEANT_OPLOT_PSCATRAJ_Y_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PSCATRAJ_Y = { "Y", 1, "Y-coordinate", "0.",
 (char*)0, 12, 0, (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_REAL,
 &_OMGEANT_OPLOT_PSCATRAJ_Y_type };
static KmParReal   _OMGEANT_OPLOT_PSCATRAJ_Z_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PSCATRAJ_Z = { "Z", 1, "Z-coordinate", "0.",
 (char*)0, 12, 0, (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_REAL,
 &_OMGEANT_OPLOT_PSCATRAJ_Z_type };
static KmParReal   _OMGEANT_OPLOT_PSCATRAJ_PX_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PSCATRAJ_PX = { "PX", 2,
 "PX - of the momentum", "300.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_OPLOT_PSCATRAJ_PX_type };
static KmParReal   _OMGEANT_OPLOT_PSCATRAJ_PY_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PSCATRAJ_PY = { "PY", 2,
 "PY - of the momentum", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_OPLOT_PSCATRAJ_PY_type };
static KmParReal   _OMGEANT_OPLOT_PSCATRAJ_PZ_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PSCATRAJ_PZ = { "PZ", 2,
 "PZ - of the momentum", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_OPLOT_PSCATRAJ_PZ_type };
static KmParameter *_OMGEANT_OPLOT_PSCATRAJ_parameters[] = {
 &_OMGEANT_OPLOT_PSCATRAJ_ID, &_OMGEANT_OPLOT_PSCATRAJ_PARA,
 &_OMGEANT_OPLOT_PSCATRAJ_TYPE, &_OMGEANT_OPLOT_PSCATRAJ_X,
 &_OMGEANT_OPLOT_PSCATRAJ_Y, &_OMGEANT_OPLOT_PSCATRAJ_Z,
 &_OMGEANT_OPLOT_PSCATRAJ_PX, &_OMGEANT_OPLOT_PSCATRAJ_PY,
 &_OMGEANT_OPLOT_PSCATRAJ_PZ };
static char *_OMGEANT_OPLOT_PSCATRAJ_guidance[] = {
 "  Fills a histogram with the amount of material in RL/.. along",
 "  the length of a track for the next event simulated. If this",
 "  flag is set then only one track is simulated for the next event." };
static KmCommand _OMGEANT_OPLOT_PSCATRAJ = { &_OMGEANT_OPLOT_PDEVIATION,
 "/OMGEANT/OPLOT/PSCATRAJ", "PSCATRAJ", 0, 2, 9, 9,
 _OMGEANT_OPLOT_PSCATRAJ_parameters, 0, 0, omxplot_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 3, _OMGEANT_OPLOT_PSCATRAJ_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParReal   _OMGEANT_OPLOT_PRIMED_X_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PRIMED_X = { "X", 1,
 "X coordinate of the point", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_OPLOT_PRIMED_X_type };
static KmParReal   _OMGEANT_OPLOT_PRIMED_Y_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PRIMED_Y = { "Y", 1,
 "Y coordinate of the point", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_OPLOT_PRIMED_Y_type };
static KmParReal   _OMGEANT_OPLOT_PRIMED_Z_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PRIMED_Z = { "Z", 1,
 "Z coordinate of the point", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_OPLOT_PRIMED_Z_type };
static KmParameter *_OMGEANT_OPLOT_PRIMED_parameters[] = {
 &_OMGEANT_OPLOT_PRIMED_X, &_OMGEANT_OPLOT_PRIMED_Y, &_OMGEANT_OPLOT_PRIMED_Z
 };
static char *_OMGEANT_OPLOT_PRIMED_guidance[] = {
 "  Prints for a given point: medium, volume names" };
static KmCommand _OMGEANT_OPLOT_PRIMED = { &_OMGEANT_OPLOT_PSCATRAJ,
 "/OMGEANT/OPLOT/PRIMED", "PRIMED", 0, 2, 3, 3,
 _OMGEANT_OPLOT_PRIMED_parameters, 0, 0, omxcntr1_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_OPLOT_PRIMED_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParReal   _OMGEANT_OPLOT_PRIMAG_X_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PRIMAG_X = { "X", 1,
 "X coordinate of the point", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_OPLOT_PRIMAG_X_type };
static KmParReal   _OMGEANT_OPLOT_PRIMAG_Y_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PRIMAG_Y = { "Y", 1,
 "Y coordinate of the point", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_OPLOT_PRIMAG_Y_type };
static KmParReal   _OMGEANT_OPLOT_PRIMAG_Z_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PRIMAG_Z = { "Z", 1,
 "Z coordinate of the point", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_OPLOT_PRIMAG_Z_type };
static KmParameter *_OMGEANT_OPLOT_PRIMAG_parameters[] = {
 &_OMGEANT_OPLOT_PRIMAG_X, &_OMGEANT_OPLOT_PRIMAG_Y, &_OMGEANT_OPLOT_PRIMAG_Z
 };
static char *_OMGEANT_OPLOT_PRIMAG_guidance[] = {
 "  Prints the magnetic field in a given point" };
static KmCommand _OMGEANT_OPLOT_PRIMAG = { &_OMGEANT_OPLOT_PRIMED,
 "/OMGEANT/OPLOT/PRIMAG", "PRIMAG", 0, 2, 3, 3,
 _OMGEANT_OPLOT_PRIMAG_parameters, 0, 0, omxcntr1_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_OPLOT_PRIMAG_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_OPLOT_PMAGF_ID_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PMAGF_ID = { "ID", 2,
 "ID of the histogram. Should be booked ", (char*)0, (char*)0, 8, 0,
 (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_INT,
 &_OMGEANT_OPLOT_PMAGF_ID_type };
static KmParInt    _OMGEANT_OPLOT_PMAGF_MAG_type = { "1", "5", "1", "5", 0 };
static KmParameter _OMGEANT_OPLOT_PMAGF_MAG = { "MAG", 3,
 "Number of the magnet", "1", (char*)0, 2, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_OPLOT_PMAGF_MAG_type };
static KmParInt    _OMGEANT_OPLOT_PMAGF_XH_type = { "1", "3", "1", "3", 0 };
static KmParameter _OMGEANT_OPLOT_PMAGF_XH = { "XH", 2,
 "Projection X of the 1/2-dim histogram (X/Y/Z=1/2/3)", "1", (char*)0, 2, 0,
 (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_INT,
 &_OMGEANT_OPLOT_PMAGF_XH_type };
static KmParInt    _OMGEANT_OPLOT_PMAGF_YH_type = { "1", "3", "1", "3", 0 };
static KmParameter _OMGEANT_OPLOT_PMAGF_YH = { "YH", 2,
 "Projection Y of the   2-dim histogram (X/Y/Z=1/2/3)", "2", (char*)0, 2, 0,
 (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_INT,
 &_OMGEANT_OPLOT_PMAGF_YH_type };
static KmParReal   _OMGEANT_OPLOT_PMAGF_X_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PMAGF_X = { "X", 1,
 "X-coordinate (in the magnet reference frame)", "0.", (char*)0, 12, 0,
 (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_REAL,
 &_OMGEANT_OPLOT_PMAGF_X_type };
static KmParReal   _OMGEANT_OPLOT_PMAGF_Y_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PMAGF_Y = { "Y", 1, "Y-coordinate", "0.",
 (char*)0, 12, 0, (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_REAL,
 &_OMGEANT_OPLOT_PMAGF_Y_type };
static KmParReal   _OMGEANT_OPLOT_PMAGF_Z_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PMAGF_Z = { "Z", 1, "Z-coordinate", "0.",
 (char*)0, 12, 0, (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_REAL,
 &_OMGEANT_OPLOT_PMAGF_Z_type };
static KmParReal   _OMGEANT_OPLOT_PMAGF_AX_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PMAGF_AX = { "AX", 2,
 " The plotted value: B=BX*AX+BY*AY+BZ*AZ", "0.", (char*)0, 12, 0, (char**)0,
 0, (char**)0, (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_OPLOT_PMAGF_AX_type };
static KmParReal   _OMGEANT_OPLOT_PMAGF_AY_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PMAGF_AY = { "AY", 2,
 " The plotted value: B=BX*AX+BY*AY+BZ*AZ", "0.", (char*)0, 12, 0, (char**)0,
 0, (char**)0, (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_OPLOT_PMAGF_AY_type };
static KmParReal   _OMGEANT_OPLOT_PMAGF_AZ_type = { (char*)0, (char*)0,
 (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_OPLOT_PMAGF_AZ = { "AZ", 2,
 " The plotted value: B=BX*AX+BY*AY+BZ*AZ", "1.", (char*)0, 12, 0, (char**)0,
 0, (char**)0, (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_OPLOT_PMAGF_AZ_type };
static KmParameter *_OMGEANT_OPLOT_PMAGF_parameters[] = {
 &_OMGEANT_OPLOT_PMAGF_ID, &_OMGEANT_OPLOT_PMAGF_MAG,
 &_OMGEANT_OPLOT_PMAGF_XH, &_OMGEANT_OPLOT_PMAGF_YH, &_OMGEANT_OPLOT_PMAGF_X,
 &_OMGEANT_OPLOT_PMAGF_Y, &_OMGEANT_OPLOT_PMAGF_Z, &_OMGEANT_OPLOT_PMAGF_AX,
 &_OMGEANT_OPLOT_PMAGF_AY, &_OMGEANT_OPLOT_PMAGF_AZ };
static char *_OMGEANT_OPLOT_PMAGF_guidance[] = {
 "  Plots 1 or 2-dimensional plot of the magnetic field in magnets 1-5",
 "  One may choose a field projection to plot.",
 "  The field component can be protted versus X,Y or Z",
 "    (or any pair for 2-dim plots)." };
static KmCommand _OMGEANT_OPLOT_PMAGF = { &_OMGEANT_OPLOT_PRIMAG,
 "/OMGEANT/OPLOT/PMAGF", "PMAGF", 0, 2, 10, 10,
 _OMGEANT_OPLOT_PMAGF_parameters, 0, 0, omxplot_, (IntFunc*)0, (SUBROUTINE*)0,
 (pCharFunc*)0, 4, _OMGEANT_OPLOT_PMAGF_guidance, 0, (char**)0, 0, (char**)0,
 0, (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_MODIFICATION_KINONE_IPAR_type = { "1", "200", "1",
 "200", 0 };
static KmParameter _OMGEANT_MODIFICATION_KINONE_IPAR = { "IPAR", 4,
 "A factor for Cherenkov photons multiplicity", (char*)0, (char*)0, 4, 0,
 (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_INT,
 &_OMGEANT_MODIFICATION_KINONE_IPAR_type };
static KmParReal   _OMGEANT_MODIFICATION_KINONE_MOM_type = { "0.", "200.",
 "0.", "200.", 0 };
static KmParameter _OMGEANT_MODIFICATION_KINONE_MOM = { "MOM", 3,
 "Central momentum, GeV", (char*)0, (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_KINONE_MOM_type };
static KmParReal   _OMGEANT_MODIFICATION_KINONE_THET_type = { "0.", "3.1416",
 "0.", "3.1416", 4 };
static KmParameter _OMGEANT_MODIFICATION_KINONE_THET = { "THET", 4,
 "Central theta angle (to Z axis), rad", (char*)0, (char*)0, 12, 0, (char**)0,
 0, (char**)0, (KmParFlag)0, KmTYPE_REAL,
 &_OMGEANT_MODIFICATION_KINONE_THET_type };
static KmParReal   _OMGEANT_MODIFICATION_KINONE_PHI_type = { "0.", "6.29",
 "0.", "6.29", 2 };
static KmParameter _OMGEANT_MODIFICATION_KINONE_PHI = { "PHI", 3,
 "Central phi   angle (proj onto XY, angle to X), rad", (char*)0, (char*)0,
 12, 0, (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_REAL,
 &_OMGEANT_MODIFICATION_KINONE_PHI_type };
static KmParReal   _OMGEANT_MODIFICATION_KINONE_DMOM_type = { "0.", "200.",
 "0.", "200.", 0 };
static KmParameter _OMGEANT_MODIFICATION_KINONE_DMOM = { "DMOM", 4,
 "Momentum width: p=p0+/-dp , GeV", (char*)0, (char*)0, 12, 0, (char**)0, 0,
 (char**)0, (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_KINONE_DMOM_type
 };
static KmParReal   _OMGEANT_MODIFICATION_KINONE_DTHET_type = { "0.", "3.1416",
 "0.", "3.1416", 4 };
static KmParameter _OMGEANT_MODIFICATION_KINONE_DTHET = { "DTHET", 5,
 "Theta    width, rad", (char*)0, (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_KINONE_DTHET_type };
static KmParReal   _OMGEANT_MODIFICATION_KINONE_DPHI_type = { "0.", "6.29",
 "0.", "6.29", 2 };
static KmParameter _OMGEANT_MODIFICATION_KINONE_DPHI = { "DPHI", 4,
 "Phi      width, rad", (char*)0, (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_KINONE_DPHI_type };
static KmParameter *_OMGEANT_MODIFICATION_KINONE_parameters[] = {
 &_OMGEANT_MODIFICATION_KINONE_IPAR, &_OMGEANT_MODIFICATION_KINONE_MOM,
 &_OMGEANT_MODIFICATION_KINONE_THET, &_OMGEANT_MODIFICATION_KINONE_PHI,
 &_OMGEANT_MODIFICATION_KINONE_DMOM, &_OMGEANT_MODIFICATION_KINONE_DTHET,
 &_OMGEANT_MODIFICATION_KINONE_DPHI };
static char *_OMGEANT_MODIFICATION_KINONE_guidance[] = {
 "  Parameters of the single particle to generate (OMKINONE)" };
static KmCommand _OMGEANT_MODIFICATION_KINONE = {  (KmCommand*)0,
 "/OMGEANT/MODIFICATION/KINONE", "KINONE", 0, 2, 7, 7,
 _OMGEANT_MODIFICATION_KINONE_parameters, 0, 0, omxcntr1_, (IntFunc*)0,
 (SUBROUTINE*)0, (pCharFunc*)0, 1, _OMGEANT_MODIFICATION_KINONE_guidance, 0,
 (char**)0, 0, (char**)0, 0, (char**)0, (char*)0, (int*)0 };

static KmParReal   _OMGEANT_MODIFICATION_CHERFAC_FAC_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_CHERFAC_FAC = { "FAC", 3,
 "A factor for Cherenkov photons multiplicity", "369.81E9", (char*)0, 12, 0,
 (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_REAL,
 &_OMGEANT_MODIFICATION_CHERFAC_FAC_type };
static KmParameter *_OMGEANT_MODIFICATION_CHERFAC_parameters[] = {
 &_OMGEANT_MODIFICATION_CHERFAC_FAC };
static char *_OMGEANT_MODIFICATION_CHERFAC_guidance[] = {
 "  Redefines the multiplicity for Cherenkov photons" };
static KmCommand _OMGEANT_MODIFICATION_CHERFAC = {
 &_OMGEANT_MODIFICATION_KINONE, "/OMGEANT/MODIFICATION/CHERFAC", "CHERFAC", 0,
 2, 1, 1, _OMGEANT_MODIFICATION_CHERFAC_parameters, 0, 0, omxcntr1_,
 (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 1,
 _OMGEANT_MODIFICATION_CHERFAC_guidance, 0, (char**)0, 0, (char**)0, 0,
 (char**)0, (char*)0, (int*)0 };

static KmParReal   _OMGEANT_MODIFICATION_BEAMMOM_B1_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_BEAMMOM_B1 = { "B1", 2,
 "minimum momentum GeV/c", (char*)0, (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_BEAMMOM_B1_type };
static KmParReal   _OMGEANT_MODIFICATION_BEAMMOM_B1_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_BEAMMOM_B1 = { "B1", 2,
 "minimum momentum GeV/c", (char*)0, (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_BEAMMOM_B1_type };
static KmParReal   _OMGEANT_MODIFICATION_BEAMMOM_SB_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_BEAMMOM_SB = { "SB", 2,
 "sigma of the distribution", (char*)0, (char*)0, 12, 0, (char**)0, 0,
 (char**)0, (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_BEAMMOM_SB_type
 };
static KmParameter *_OMGEANT_MODIFICATION_BEAMMOM_parameters[] = {
 &_OMGEANT_MODIFICATION_BEAMMOM_B1, &_OMGEANT_MODIFICATION_BEAMMOM_B1,
 &_OMGEANT_MODIFICATION_BEAMMOM_SB };
static char *_OMGEANT_MODIFICATION_BEAMMOM_guidance[] = {
 "  Redefines the beam momentum (it the beam is defined as a gaussiqan" };
static KmCommand _OMGEANT_MODIFICATION_BEAMMOM = {
 &_OMGEANT_MODIFICATION_CHERFAC, "/OMGEANT/MODIFICATION/BEAMMOM", "BEAMMOM",
 0, 2, 3, 3, _OMGEANT_MODIFICATION_BEAMMOM_parameters, 0, 0, omxcntr1_,
 (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 1,
 _OMGEANT_MODIFICATION_BEAMMOM_guidance, 0, (char**)0, 0, (char**)0, 0,
 (char**)0, (char*)0, (int*)0 };

static KmParReal   _OMGEANT_MODIFICATION_MOTTANGL_THETMIN_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MOTTANGL_THETMIN = { "THETMIN", 7,
 "theta minimum", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_MOTTANGL_THETMIN_type };
static KmParReal   _OMGEANT_MODIFICATION_MOTTANGL_THETMAX_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MOTTANGL_THETMAX = { "THETMAX", 7,
 "theta maximum", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_MOTTANGL_THETMAX_type };
static KmParReal   _OMGEANT_MODIFICATION_MOTTANGL_PHIMIN_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MOTTANGL_PHIMIN = { "PHIMIN", 6,
 "phi minimum", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0, (KmParFlag)0,
 KmTYPE_REAL, &_OMGEANT_MODIFICATION_MOTTANGL_PHIMIN_type };
static KmParReal   _OMGEANT_MODIFICATION_MOTTANGL_PHIMAX_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MOTTANGL_PHIMAX = { "PHIMAX", 6,
 "phi maximum", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0, (KmParFlag)0,
 KmTYPE_REAL, &_OMGEANT_MODIFICATION_MOTTANGL_PHIMAX_type };
static KmParameter *_OMGEANT_MODIFICATION_MOTTANGL_parameters[] = {
 &_OMGEANT_MODIFICATION_MOTTANGL_THETMIN,
 &_OMGEANT_MODIFICATION_MOTTANGL_THETMAX,
 &_OMGEANT_MODIFICATION_MOTTANGL_PHIMIN,
 &_OMGEANT_MODIFICATION_MOTTANGL_PHIMAX };
static char *_OMGEANT_MODIFICATION_MOTTANGL_guidance[] = {
 "  Changes the range of Mott scattering angles in Lab" };
static KmCommand _OMGEANT_MODIFICATION_MOTTANGL = {
 &_OMGEANT_MODIFICATION_BEAMMOM, "/OMGEANT/MODIFICATION/MOTTANGL", "MOTTANGL",
 0, 2, 4, 4, _OMGEANT_MODIFICATION_MOTTANGL_parameters, 0, 0, omxcntr1_,
 (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 1,
 _OMGEANT_MODIFICATION_MOTTANGL_guidance, 0, (char**)0, 0, (char**)0, 0,
 (char**)0, (char*)0, (int*)0 };

static KmParReal   _OMGEANT_MODIFICATION_MOLLANGL_THETMIN_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MOLLANGL_THETMIN = { "THETMIN", 7,
 "theta minimum", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_MOLLANGL_THETMIN_type };
static KmParReal   _OMGEANT_MODIFICATION_MOLLANGL_THETMAX_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MOLLANGL_THETMAX = { "THETMAX", 7,
 "theta maximum", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_MOLLANGL_THETMAX_type };
static KmParReal   _OMGEANT_MODIFICATION_MOLLANGL_PHIMIN_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MOLLANGL_PHIMIN = { "PHIMIN", 6,
 "phi minimum", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0, (KmParFlag)0,
 KmTYPE_REAL, &_OMGEANT_MODIFICATION_MOLLANGL_PHIMIN_type };
static KmParReal   _OMGEANT_MODIFICATION_MOLLANGL_PHIMAX_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MOLLANGL_PHIMAX = { "PHIMAX", 6,
 "phi maximum", "0.", (char*)0, 12, 0, (char**)0, 0, (char**)0, (KmParFlag)0,
 KmTYPE_REAL, &_OMGEANT_MODIFICATION_MOLLANGL_PHIMAX_type };
static KmParameter *_OMGEANT_MODIFICATION_MOLLANGL_parameters[] = {
 &_OMGEANT_MODIFICATION_MOLLANGL_THETMIN,
 &_OMGEANT_MODIFICATION_MOLLANGL_THETMAX,
 &_OMGEANT_MODIFICATION_MOLLANGL_PHIMIN,
 &_OMGEANT_MODIFICATION_MOLLANGL_PHIMAX };
static char *_OMGEANT_MODIFICATION_MOLLANGL_guidance[] = {
 "  Changes the range of Moller scattering angles in CM" };
static KmCommand _OMGEANT_MODIFICATION_MOLLANGL = {
 &_OMGEANT_MODIFICATION_MOTTANGL, "/OMGEANT/MODIFICATION/MOLLANGL",
 "MOLLANGL", 0, 2, 4, 4, _OMGEANT_MODIFICATION_MOLLANGL_parameters, 0, 0,
 omxcntr1_, (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 1,
 _OMGEANT_MODIFICATION_MOLLANGL_guidance, 0, (char**)0, 0, (char**)0, 0,
 (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_MODIFICATION_MAGSIZE_MAF_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MAGSIZE_MAF = { "MAF", 3,
 "the magnet number ", (char*)0, (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_MODIFICATION_MAGSIZE_MAF_type };
static KmParReal   _OMGEANT_MODIFICATION_MAGSIZE_X_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MAGSIZE_X = { "X", 1,
 "Full size in X", "-999.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_MAGSIZE_X_type };
static KmParReal   _OMGEANT_MODIFICATION_MAGSIZE_Y_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MAGSIZE_Y = { "Y", 1,
 "Full size in Y", "-999.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_MAGSIZE_Y_type };
static KmParReal   _OMGEANT_MODIFICATION_MAGSIZE_Z_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MAGSIZE_Z = { "Z", 1,
 "Full size in Z", "-999.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_MAGSIZE_Z_type };
static KmParameter *_OMGEANT_MODIFICATION_MAGSIZE_parameters[] = {
 &_OMGEANT_MODIFICATION_MAGSIZE_MAF, &_OMGEANT_MODIFICATION_MAGSIZE_X,
 &_OMGEANT_MODIFICATION_MAGSIZE_Y, &_OMGEANT_MODIFICATION_MAGSIZE_Z };
static char *_OMGEANT_MODIFICATION_MAGSIZE_guidance[] = {
 "  Changes the dimensions of the magnetic field (PMOLMAG(2-4,mag)",
 "  Negative values are ignored." };
static KmCommand _OMGEANT_MODIFICATION_MAGSIZE = {
 &_OMGEANT_MODIFICATION_MOLLANGL, "/OMGEANT/MODIFICATION/MAGSIZE", "MAGSIZE",
 0, 2, 4, 4, _OMGEANT_MODIFICATION_MAGSIZE_parameters, 0, 0, omxcntr1_,
 (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 2,
 _OMGEANT_MODIFICATION_MAGSIZE_guidance, 0, (char**)0, 0, (char**)0, 0,
 (char**)0, (char*)0, (int*)0 };

static KmParInt    _OMGEANT_MODIFICATION_MAGFIELD_MAF_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MAGFIELD_MAF = { "MAF", 3,
 "the magnet number ", (char*)0, (char*)0, 8, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_INT, &_OMGEANT_MODIFICATION_MAGFIELD_MAF_type };
static KmParReal   _OMGEANT_MODIFICATION_MAGFIELD_FIELD_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MAGFIELD_FIELD = { "FIELD", 5,
 "Field kGs", "-9999.", (char*)0, 12, 0, (char**)0, 0, (char**)0,
 (KmParFlag)0, KmTYPE_REAL, &_OMGEANT_MODIFICATION_MAGFIELD_FIELD_type };
static KmParReal   _OMGEANT_MODIFICATION_MAGFIELD_FLAG1_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MAGFIELD_FLAG1 = { "FLAG1", 5,
 "For dipole: flag1=1 - longitudinal component included", "-9999.", (char*)0,
 12, 0, (char**)0, 0, (char**)0, (KmParFlag)0, KmTYPE_REAL,
 &_OMGEANT_MODIFICATION_MAGFIELD_FLAG1_type };
static KmParReal   _OMGEANT_MODIFICATION_MAGFIELD_FLAG2_type = { (char*)0,
 (char*)0, (char*)0, (char*)0, 0 };
static KmParameter _OMGEANT_MODIFICATION_MAGFIELD_FLAG2 = { "FLAG2", 5,
 "flag2", "-9999.", (char*)0, 12, 0, (char**)0, 0, (char**)0, (KmParFlag)0,
 KmTYPE_REAL, &_OMGEANT_MODIFICATION_MAGFIELD_FLAG2_type };
static KmParameter *_OMGEANT_MODIFICATION_MAGFIELD_parameters[] = {
 &_OMGEANT_MODIFICATION_MAGFIELD_MAF, &_OMGEANT_MODIFICATION_MAGFIELD_FIELD,
 &_OMGEANT_MODIFICATION_MAGFIELD_FLAG1, &_OMGEANT_MODIFICATION_MAGFIELD_FLAG2
 };
static char *_OMGEANT_MODIFICATION_MAGFIELD_guidance[] = {
 "  Changes the values of the field (AMAGPAR(5-7,mag))" };
static KmCommand _OMGEANT_MODIFICATION_MAGFIELD = {
 &_OMGEANT_MODIFICATION_MAGSIZE, "/OMGEANT/MODIFICATION/MAGFIELD", "MAGFIELD",
 0, 2, 4, 2, _OMGEANT_MODIFICATION_MAGFIELD_parameters, 0, 0, omxcntr1_,
 (IntFunc*)0, (SUBROUTINE*)0, (pCharFunc*)0, 1,
 _OMGEANT_MODIFICATION_MAGFIELD_guidance, 0, (char**)0, 0, (char**)0, 0,
 (char**)0, (char*)0, (int*)0 };

static char *_OMGEANT_MODIFICATION_guidance[] = {
 "Modifications of some preset values" };
static KmMenu _OMGEANT_MODIFICATION = {  (KmMenu*)0,  (KmMenu*)0,
 "/OMGEANT/MODIFICATION", "MODIFICATION", 2, &_OMGEANT_MODIFICATION_MAGFIELD,
 1, _OMGEANT_MODIFICATION_guidance, 0, (char**)0, 0, (char**)0 };

static char *_OMGEANT_OPLOT_guidance[] = { "Plot/print different values" };
static KmMenu _OMGEANT_OPLOT = { &_OMGEANT_MODIFICATION,  (KmMenu*)0,
 "/OMGEANT/OPLOT", "OPLOT", 2, &_OMGEANT_OPLOT_PMAGF, 1,
 _OMGEANT_OPLOT_guidance, 0, (char**)0, 0, (char**)0 };

static char *_OMGEANT_CONTROL_guidance[] = { "Control flags and commands" };
static KmMenu _OMGEANT_CONTROL = { &_OMGEANT_OPLOT,  (KmMenu*)0,
 "/OMGEANT/CONTROL", "CONTROL", 2, &_OMGEANT_CONTROL_TKINE1, 1,
 _OMGEANT_CONTROL_guidance, 0, (char**)0, 0, (char**)0 };

static char *_OMGEANT_DRAW_guidance[] = { "Drawing commands" };
static KmMenu _OMGEANT_DRAW = { &_OMGEANT_CONTROL,  (KmMenu*)0,
 "/OMGEANT/DRAW", "DRAW", 2, &_OMGEANT_DRAW_DDIGI, 1, _OMGEANT_DRAW_guidance,
 0, (char**)0, 0, (char**)0 };

static char *_OMGEANT_guidance[] = { "Commands for OMGEANT" };
static KmMenu _OMGEANT = {  (KmMenu*)0, &_OMGEANT_DRAW, "/OMGEANT", "OMGEANT",
 1,  (KmCommand*)0, 1, _OMGEANT_guidance, 0, (char**)0, 0, (char**)0 };

  klnkmenu( &_OMGEANT, 950303 );
}


